# Generated by Django 6.0.5 on 2026-07-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='outlet_ticket_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
