# Generated by Django 6.0.5 on 2026-05-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='tickets.section')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='concern_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.concerntype'),
        ),
    ]
