# Generated by Django 6.0.5 on 2026-06-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_concerntype_ticket_concern_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
    ]
