# Generated by Django 6.0.5 on 2026-07-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_devicetoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='concerntype',
            old_name='section',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='section',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='section',
            new_name='department',
        ),
    ]
