# Generated by Django 6.0.5 on 2026-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
