# Generated by Django 6.0.5 on 2026-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
