# Generated by Django 6.0.5 on 2026-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_admin_note_ticket_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='outlet',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
