# Generated by Django 6.0.5 on 2026-06-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='outlet',
        ),
    ]
