# Generated by Django 6.0.5 on 2026-06-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='outlet',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
