# Generated by Django 6.0.5 on 2026-07-12 14:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='attachment'),
        ),
    ]
