# Generated by Django 6.0.5 on 2026-07-12 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
