# Generated by Django 6.0.5 on 2026-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('outlet', 'Outlet')], default='outlet', max_length=20),
        ),
    ]
