# Generated by Django 6.0.5 on 2026-06-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
