# Generated by Django 6.0.5 on 2026-06-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticketstatuslog_ticket'),
    ]

    operations = [
    ]
