# Generated by Django 6.0.5 on 2026-06-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20260617_1552'),
    ]

    operations = [
    ]
