# Generated by Django 6.0.5 on 2026-08-07 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='additional_technicians',
            field=models.ManyToManyField(blank=True, related_name='additional_tickets', to='tickets.technician'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tickets', to='tickets.technician'),
        ),
        migrations.CreateModel(
            name='TicketAdditionalAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.technician')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_assignment_logs', to='tickets.ticket')),
            ],
        ),
    ]
