# Generated by Django 6.0.5 on 2026-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_additional_technicians_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='tickets.department'),
        ),
    ]
